[package]
name = "atc-recognition-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15"
regex = "1.11"
ringbuf = "0.4"
rubato = "0.16"
serde = { workspace = true }
serde_json = "1.0"
thiserror = "2.0"
whisper-rs = { version = "0.14", features = ["vulkan"] }
